# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tiJRNoZoVoiyd2D2fEuDeAKT_qZxxyfl
"""

import numpy as np
import matplotlib.pyplot as plt

a = np.arange(1, 50, 0.1)

plt.plot(a)

