# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tiJRNoZoVoiyd2D2fEuDeAKT_qZxxyfl
"""

import numpy as np
import matplotlib.pyplot as plt

a = np.arange(1, 50, 0.1)

plt.plot(a)

# new feature
 
 b = 0

# feature 1

<<<<<<< HEAD
c = 0

# feature 2

d = 0
=======
>>>>>>> c31f0910d73556854e6137621e57112f7f826f1a
